# Generated by Django 5.2.3 on 2025-06-26 12:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('url', models.CharField(max_length=255, unique=True)),
                ('shard', models.CharField(max_length=255)),
                ('query', models.CharField(max_length=255)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='api.category')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('wb_id', models.BigIntegerField(unique=True)),
                ('brand', models.CharField(db_index=True, max_length=255)),
                ('supplier_id', models.BigIntegerField(db_index=True)),
                ('review_rating', models.PositiveIntegerField(db_index=True, default=0)),
                ('feedbacks', models.PositiveIntegerField(db_index=True, default=0)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='api.category')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('size_id', models.BigIntegerField(db_index=True)),
                ('price', models.DecimalField(db_index=True, decimal_places=2, default=0, max_digits=12)),
                ('discounted_price', models.DecimalField(db_index=True, decimal_places=2, default=0, max_digits=12)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sizes', to='api.product')),
            ],
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['shard'], name='api_categor_shard_ac0a09_idx'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['query'], name='api_categor_query_f5959d_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['review_rating'], name='api_product_review__5c0fe5_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['feedbacks'], name='api_product_feedbac_66aa9c_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['brand'], name='api_product_brand_b832b2_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['review_rating', 'feedbacks'], name='api_product_review__2dff94_idx'),
        ),
        migrations.AddIndex(
            model_name='size',
            index=models.Index(fields=['price'], name='api_size_price_3822c3_idx'),
        ),
        migrations.AddIndex(
            model_name='size',
            index=models.Index(fields=['discounted_price'], name='api_size_discoun_eb3493_idx'),
        ),
        migrations.AddIndex(
            model_name='size',
            index=models.Index(fields=['price', 'discounted_price'], name='api_size_price_0cf907_idx'),
        ),
    ]
