# Generated by Django 5.2.3 on 2025-06-26 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='wb_id',
            field=models.BigIntegerField(default=0, unique=True),
            preserve_default=False,
        ),
    ]
