# Generated by Django 5.2.3 on 2025-06-26 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_category_wb_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.RenameField(
            model_name='product',
            old_name='supplier_id',
            new_name='brand_id',
        ),
    ]
