# Generated by Django 5.2.3 on 2025-06-27 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_category_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='size',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
