# Generated by Django 5.2.3 on 2025-06-30 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_product_parsed_from_alter_product_review_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.CharField(db_index=True, max_length=255)),
                ('count', models.PositiveIntegerField(default=1)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_search', models.DateTimeField(auto_now=True)),
                ('products', models.ManyToManyField(related_name='search_queries', to='api.product')),
            ],
            options={
                'verbose_name_plural': 'SearchQueries',
                'ordering': ['-last_search'],
            },
        ),
    ]
