# Generated by Django 5.2.3 on 2025-07-01 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_searchquery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='query',
            field=models.CharField(max_length=2048),
        ),
        migrations.AlterField(
            model_name='searchquery',
            name='query',
            field=models.CharField(db_index=True, max_length=2048),
        ),
    ]
