# Generated by Django 5.2.3 on 2025-07-02 07:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_category_query_alter_searchquery_query'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='api.category'),
        ),
        migrations.AlterField(
            model_name='searchquery',
            name='products',
            field=models.ManyToManyField(blank=True, null=True, related_name='search_queries', to='api.product'),
        ),
    ]
